### ISSUE TITLE
make_really_tall_trees.py script  always running

### ISSUE THREAD

**Issue by xf78** [phbradley/tcr-dist#35]
Hi!dear team,
the make_really_tall_trees.py script  always running,but there is no error message,see as fellow:
![图片](https://user-images.githubusercontent.com/13416926/77240647-162e2700-6c23-11ea-9946-b5a0c33f8ce5.png)

my input file has 11762 clones,do I have too much clones? the script has been running for two days,any good suggestions? thanks

**Comment by jeremycfd** [comment]
I've experienced this when trying to plot too many clones in a tree. I usually use CTRL-C to kill that one process of the script.
