### ISSUE TITLE
make_10x_clones_file.py issue

### ISSUE THREAD

**Issue by crushseven-7** [phbradley/tcr-dist#37]
When this python script invokes file_converter.py, I guess it may use the wrong--check_genes flag cause it is dont_check_genes in file_converter.py.

**Comment by phbradley** [comment]
Oh, good catch. Sorry about that-- I changed it in one place and didn't catch the other. I think it's fixed now.

**Comment by crushseven-7** [comment]
by the way, really appreciate for your excellent pipeline, I will close the issue
