### ISSUE TITLE
Estimation of TCRdiv

### ISSUE THREAD

**Issue by bravib** [phbradley/tcr-dist#39]
Good evening, 
after reading your paper I would be interested in estimating TCRdiv of a series of epitope-specific repertoires, however I do not find a script dedicated only to it without the need of running the full analysis. Could you please help me with this? Does one need also the alpha-chain to estimate TCRdiv? 
Many thanks, best regards, 
Barbara

**Comment by phbradley** [comment]
Hi Barbara,
Thanks for your query. Do you have paired (alpha/beta) data or just single chain?

**Comment by bravib** [comment]
I actually have only beta chains, so I was wondering if the TCRdiv measure is applicable, limiting the evaluation of the distance to these chains. 
Many thanks, 
Barbara

**Comment by phbradley** [comment]
OK, one more question-- roughly how big are your repertoires? Hundreds, thousands, millions? I also have a C++ repository that can compute TCRdiv and scale to larger datasets...

**Comment by bravib** [comment]
I see, in terms of unique sequences they are between 25000 and 50000 and I look at the CDR3 region (while I know that TCRdist is calibrated not only on the CDR3). Thanks a lot for your help, 
Barbara

**Comment by phbradley** [comment]
OK, and do you only have the CDR3 or do you mean that when you look only at the CDR3 you have 25000 to 50000 unique sequences?

**Comment by bravib** [comment]
Ah sorry, I mean that I have only the CDR3 and they are roughly between 25000 and 50000 unique ones.

**Comment by phbradley** [comment]
Hi Barbara, without the V genes it's not really possible to compute TCRdist. You could try something like a simple Hamming distance or Levenshtein distance on the CDR3s and try using the same formula for TCRdiv, but I don't have code to help with that. Sorry!

**Comment by bravib** [comment]
Yes, I was already thinking about proceeding in this way, many thanks for your replies. 
Barbara
