### ISSUE TITLE
setup_gammadelta_db.py issue

### ISSUE THREAD

**Issue by crushseven-7** [phbradley/tcr-dist#40]
Hi there,
When I setup gammadelta database, I found in line 66 still set your own path. It might better provide file in github.
Best,
Yan

**Comment by phbradley** [comment]
Hi Yan-- sorry for the confusion. That script ("setup_gammadelta_db.py") was just for making the database file, it's not needed anymore. To analyze gamma deltas you just need to uncomment this line: 

https://github.com/phbradley/tcr-dist/blob/master/basic.py#L36 

and comment out this line

https://github.com/phbradley/tcr-dist/blob/master/basic.py#L35

The database file ("gammadelta_db.tsv") is already in the db/ directory after you run setup.py.

**Comment by crushseven-7** [comment]
many thanks! I might use the old version so I construct "gammadelta_db.tsv" by myself.
